# Node.js
- task: GitVersion@5
  inputs:
    versionSpec: '5.0.0'
    includePrerelease: true

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- group: ENV_GLOBAL

pool:
  name: k8s-azure-devops-agent

# pool:
#   vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'

- script: |
    echo "Exemplo de vari치vel secreta: $dockerHubUsername"
    echo "Exemplo de vari치vel secreta: $(dockerHubUsername)"
    echo "Exemplo de vari치vel secreta: $dockerHubPassword"
    echo "Exemplo de vari치vel secreta: $(dockerHubPassword)"

- script: echo "Build and Docker push completed"
  displayName: 'Completion message'